apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      imagePullSecrets:
        - name: "aliyun-secret"
      containers:
      - image: registry.cn-beijing.aliyuncs.com/zx-common/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
